# Executes prepare submission script
echo "Executing submission preparation script (prepare_C2M2_submission.py)"
python prepare_C2M2_submission.py

# Creates frictionless validation directory.
if [[ ! -e "frictionless_validation" ]]; then
    echo "Creating frictionless_validation directory"
    mkdir frictionless_validation
else
    echo "frictionless_validation already exists"
    echo "Clearing frictionless_validation directory"
    rm -rf frictionless_validation/*
fi

# Moves data files and generated files to validation directory
echo "Copying generated term tables and draft submission tables to frictionless_validation"
cp autogenerated_C2M2_term_tables/*.tsv  frictionless_validation
cp draft_C2M2_submission_TSVs/*.tsv      frictionless_validation

# Moves the C2M2 file used to validate the submitted files
echo "Copying c2m2 schema json to frictionless_validation"
cp C2M2_datapackage.json                 frictionless_validation