# Executes prepare submission script
python prepare_C2M2_submission.py

# Creates frictionless validation directory.
if [[ ! -e "frictionless_validation" ]]; then
    mkdir frictionless_validation
else
    echo "frictionless_validation already exists."
fi

# Moves data files and generated files to validation directory
cp autogenerated_C2M2_term_tables/*.tsv  frictionless_validation
cp draft_C2M2_submission_TSVs/*.tsv      frictionless_validation

# Moves the C2M2 file used to validate the submitted files
cp C2M2_datapackage.json                 frictionless_validation